### ISSUE TITLE
Compare performances of different hash functions for task distribution

### ISSUE THREAD

**Issue by victorvianna** [cauimsouza/network-join#2]
https://courses.csail.mit.edu/6.006/spring11/rec/rec05.pdf
https://www.ida.liu.se/opendsa/OpenDSA/Books/TDDI16F16/html/HashFuncExamp.html#

**Comment by cauimsouza** [comment]
Comparison of three different hash functions: https://drive.google.com/open?id=1gzkfy_MsZpBsnxUzF6H7sVY6daenAAlz

Useful links: 
https://www.strchr.com/hash_functions
https://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed
